
resources:
- name: anubot
  type: git
  source:
    uri: https://github.com/jasonkeene/anubot
    branch: master

jobs:
- name: unit-tests
  public: true
  plan:
  - get: anubot
    trigger: true
  - task: unit-tests
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/build
          tag: latest
      platform: linux
      inputs:
      - name: anubot
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e
          cd anubot
          export GOPATH=$PWD
          export PATH=$PWD/bin:$PWD/app/node_modules/.bin:$PATH
          ./test.sh ci

- name: build
  public: true
  plan:
  - get: anubot
    trigger: true
    passed:
    - unit-tests
  - aggregate:
    - task: build-api
      config:
        image_resource:
          type: docker-image
          source:
            repository: anubot/build
            tag: latest
        platform: linux
        inputs:
        - name: anubot
        outputs:
        - name: api
        run:
          path: bash
          args:
          - -c
          - |
            #!/bin/bash
            set -e
            export GOPATH=$PWD/anubot
            GOOS=linux GOARCH=amd64 go build -o api/api_linux_amd64 anubot/cmd/api
  - task: upload-artifacts
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/aws
          tag: latest
      platform: linux
      inputs:
      - name: anubot
      - name: api
      params:
        AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e
          pushd anubot > /dev/null
            sha=$(git rev-parse @)
          popd > /dev/null
          mkdir "$sha"
          cp -R api "$sha/"
          aws s3 sync "$sha" "s3://anubot/builds/$sha"
