
resources:
- name: anubot
  type: git
  source:
    uri: https://github.com/jasonkeene/anubot
    branch: master

- name: anubot-server
  type: git
  source:
    uri: https://github.com/jasonkeene/anubot-server
    branch: master

- name: anubot-migrations
  type: git
  source:
    uri: https://github.com/jasonkeene/anubot-server
    branch: master
    paths:
    - store/migrations/*.sql

- name: migrate-image
  type: docker-image
  source:
    repository: anubot/migrate
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}

- name: migrate-image-dockerfile
  type: git
  source:
    uri: https://github.com/jasonkeene/anubot-ci
    branch: master
    paths:
    - docker-images/migrate

- name: api-image
  type: docker-image
  source:
    repository: anubot/api
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}

- name: api-image-dockerfile
  type: git
  source:
    uri: https://github.com/jasonkeene/anubot-ci
    branch: master
    paths:
    - docker-images/api

jobs:
- name: test-client
  public: true
  plan:
  - get: anubot
    trigger: true
  - task: test
    config:
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: latest
      platform: linux
      inputs:
      - name: anubot
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          cd anubot
          export PATH="$PWD/node_modules/.bin:$PATH"
          scripts/test.sh ci

- name: test-server
  public: true
  plan:
  - get: anubot-server
    trigger: true
  - task: test
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/test
          tag: latest
      platform: linux
      inputs:
      - name: anubot-server
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          mkdir -p anubot-workspace/src/github.com/jasonkeene
          cp -R anubot-server anubot-workspace/src/github.com/jasonkeene/

          cd anubot-workspace
          export GOPATH="$PWD"
          export PATH="$PWD/bin:$PATH"
          go get -u github.com/golang/dep/...

          cd src/github.com/jasonkeene/anubot-server
          dep ensure
          scripts/test.sh ci

- name: build-migrations
  public: true
  plan:
  - aggregate:
    - get: anubot-migrations
      trigger: true
    - get: migrate-image-dockerfile
      trigger: true
  - task: build-migrate-image
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/build
          tag: latest
      platform: linux
      inputs:
      - name: anubot-migrations
      - name: migrate-image-dockerfile
      outputs:
      - name: build-migrate-image
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          mkdir -p build-migrate-image/build/migrations
          cp -R migrate-image-dockerfile/docker-images/migrate/* build-migrate-image/build/
          cp anubot-migrations/store/migrations/*.sql build-migrate-image/build/migrations/

          pushd anubot-migrations > /dev/null
            sha=$(git rev-parse @)
          popd > /dev/null
          echo "$sha" > build-migrate-image/tag
  - put: migrate-image
    params:
      build: build-migrate-image/build
      tag: build-migrate-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: migrate
  plan:
  - get: anubot-migrations
    passed:
    - build-migrations
  - task: migrate
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/build
          tag: latest
      platform: linux
      inputs:
      - name: anubot-migrations
      params:
        PROD_KEY: {{prod_key}}
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          pushd anubot-migrations > /dev/null
            sha=$(git rev-parse @)
          popd > /dev/null

          mkdir -p ~/.ssh
          ssh-keyscan -Hp 42224 api.anubot.io >> ~/.ssh/known_hosts
          echo "$PROD_KEY" > id_rsa
          chmod 400 id_rsa
          echo "MIGRATE_TAG=$sha" | ssh core@api.anubot.io -i id_rsa -p 42224 "cat > /home/core/migrate-env; sudo systemctl restart migrate"

- name: build-server
  public: true
  plan:
  - aggregate:
    - get: anubot-server
      trigger: true
      passed:
      - test-server
    - get: api-image-dockerfile
      trigger: true
  - task: build-api
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/build
          tag: latest
      platform: linux
      inputs:
      - name: anubot-server
      outputs:
      - name: api
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          mkdir -p anubot-workspace/src/github.com/jasonkeene
          cp -R anubot-server anubot-workspace/src/github.com/jasonkeene/

          pushd anubot-workspace > /dev/null
            export GOPATH="$PWD"
            export PATH="$PWD/bin:$PATH"
            go get -u github.com/golang/dep/...
            pushd src/github.com/jasonkeene/anubot-server
              dep ensure
            popd
          popd > /dev/null

          GOOS=linux GOARCH=amd64 go build -o api/api_linux_amd64 github.com/jasonkeene/anubot-server/cmd/api
  - task: upload-artifacts
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/aws
          tag: latest
      platform: linux
      inputs:
      - name: anubot-server
      - name: api
      params:
        AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          pushd anubot-server > /dev/null
            sha=$(git rev-parse @)
          popd > /dev/null

          mkdir "$sha"
          cp -R api "$sha/"

          aws s3 sync "$sha" "s3://anubot/builds/$sha"
  - task: build-api-image
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/build
          tag: latest
      platform: linux
      inputs:
      - name: anubot-server
      - name: api
      - name: api-image-dockerfile
      outputs:
      - name: build-api-image
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          mkdir build-api-image/build
          cp -R api-image-dockerfile/docker-images/api/* build-api-image/build/

          cp api/api_linux_amd64 build-api-image/build/api

          pushd anubot-server > /dev/null
            sha=$(git rev-parse @)
          popd > /dev/null
          echo "$sha" > build-api-image/tag
  - put: api-image
    params:
      build: build-api-image/build
      tag: build-api-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: deploy-server
  plan:
  - get: anubot-server
    passed:
    - build-server
  - task: deploy-server
    config:
      image_resource:
        type: docker-image
        source:
          repository: anubot/build
          tag: latest
      platform: linux
      inputs:
      - name: anubot-server
      params:
        PROD_KEY: {{prod_key}}
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -e

          pushd anubot-server > /dev/null
            sha=$(git rev-parse @)
          popd > /dev/null

          mkdir -p ~/.ssh
          ssh-keyscan -Hp 42224 api.anubot.io >> ~/.ssh/known_hosts
          echo "$PROD_KEY" > id_rsa
          chmod 400 id_rsa
          echo "API_TAG=$sha" | ssh core@api.anubot.io -i id_rsa -p 42224 "cat > /home/core/api-env; sudo systemctl restart api"
